config/routes.rb
Rails.application.routes.draw do
  root 'seasons#show', id: Season.current_id
  resources :seasons
  resources :courses
  resources :golfers do
    get 'events' => 'golfers#events'
  end
  resources :headlines, only: [:new, :create, :destroy]
  resources :match_play_matchups, only: [:edit, :update]
  resources :tournaments 
  resources :ryder_cup_sessions do
    resources :ryder_cup_rounds
  end
  resources :season_tournaments, :path => "events" do
    resources :golfer_events
  end
  get 'record_book' => 'records#index'
  get 'course_difficulty' => 'courses#difficulty_rankings'
  get 'ryder_cup/:id' => 'ryder_cups#show', as: :ryder_cup
  get 'schedule/:id' => 'season_tournaments#schedule',  as: :schedule
  get 'events/:id/show_matchups' => 'season_tournaments#match_play', as: :match_play
  get 'events/:id/generate_matchups' => 'season_tournaments#generate_matchups', as: :generate_matchups
  get 'events/:id/finalize_match_play' => 'season_tournaments#finalize_match_play', as: :finalize_match_play
  get 'roster' => 'golfers#index'
  get 'finalize/:id' => 'season_tournaments#finalize', as: :finalize_event
  get 'unfinalize/:id' => 'season_tournaments#unfinalize', as: :unfinalize_event
  get 'select_default_course' => 'season_tournaments#select_default_course'
  match 'active_headlines' => 'headlines#active_headlines', via: [:get, :post]
end 

app/models/season_tournament.rb
class SeasonTournament < ApplicationRecord
  include PointsCalculator
  belongs_to :society
  belongs_to :tournament
  belongs_to :season
  belongs_to :course
  has_many :event_winners
  has_many :headlines
  has_many :golfers, through: :event_winners
  has_many :golfer_events, dependent: :destroy
  has_many :golfer_rounds, dependent: :destroy
  has_many :match_play_matchups, dependent: :destroy
  validates :season_order, numericality: { only_integer: true }
  validates_uniqueness_of :season_id, scope: %i[tournament_id]
  validates_uniqueness_of :start_date, scope: %i[season_id]
  
  def tournament_name
    tournament.current_name(year)
  end
  
  def course_name
    course.name
  end
  
  def year
    season.year
  end
  
  def type_stub
    if event_level
      event_level[0].upcase
    end
  end
  
  def tournament_name_with_year
    "#{tournament_name} (#{year})"
  end
  
  def update_event_level
    self.event_level = tournament.tournament_level.name.downcase
    save
  end
  
  def display_winners
    if event_winners.count < 1
      "N/A"
    elsif event_winners.count > 1
      winners_string = event_winners.first.golfer.name
      event_winners.drop(1).each do |winner|
        winners_string += ", #{winner.golfer.name}"
      end
      winners_string
    else
      event_winners.first.golfer.name
    end
  end
  
  def winning_score
    score = golfer_events.order(score: :asc).first.score if golfer_events.count > 0
    score ||= "N/A"
  end
  
  def winning_score_to_par
    ScoreToPar.convert_score_to_par(winning_score, course.par * rounds) if winning_score != "N/A"
  end
  
  def points_hash
    case tournament.tournament_level_id
    when 1
      {"1" => 500,
       "2" => 300,
       "3" => 190,
       "4" => 135,
       "5" => 110,
       "6" => 100,
       "7" => 90,
       "8" => 85,
       "9" => 80,
       "10" => 75
      }
    when 2
      {"1" => 550,
       "2" => 315,
       "3" => 200,
       "4" => 140,
       "5" => 115,
       "6" => 105,
       "7" => 95,
       "8" => 89,
       "9" => 83,
       "10" => 78
      }
    when 3
      {"1" => 600,
       "2" => 330,
       "3" => 210,
       "4" => 150,
       "5" => 120,
       "6" => 110,
       "7" => 100,
       "8" => 94,
       "9" => 88,
       "10" => 82
      }
    when 4
      {"1" => 2000,
       "2" => 1200,
       "3" => 760,
       "4" => 540,
       "5" => 440,
       "6" => 400,
       "7" => 360,
       "8" => 340,
       "9" => 320,
       "10" => 300
      }
    else
      {"1" => 1000,
       "2" => 600,
       "3" => 380,
       "4" => 270,
       "5" => 220,
       "6" => 200,
       "7" => 180,
       "8" => 170,
       "9" => 160,
       "10" => 150
      }
    end
  end
  
  def finalize_event
    winner_name = nil
    winner_score = nil
    golfer_events.each do |event|
      if !event.completed
        return false
      end
      event.calculate_finish
      event.calculate_points
      event.save
      if event.finish == 1
        event_winner = EventWinner.new(golfer: event.golfer, season_tournament: self, golfer_season: event.golfer_season,
                                       event_level: self.event_level)
        event_winner.save
        event.golfer.update_victory_count
        winner_name = event.golfer.name
        winner_score = event.display_score_to_par
      end
    end
    headline = headlines.new()
    headline.generate_event_winner_story(winner_name, tournament_name, winner_score)
    season.golfer_seasons.each { |g| g.update_season }
    calculate_season_points season.year
    self.finalized = true
    unless self.save
      return false
    end
    calculate_season_points season.year
    Record.generate_all_records
    true
  end
  
  def generate_matchups
    if !match_play || season.golfer_seasons.count < 8
      return false
    end
    case current_round
    when 0 || nil
      if match_round_of_eight
        self.current_round += 1
        self.save
      else return false
      end
    when 1
      if match_semi_finals
        self.current_round += 1
        self.save
      else return false
      end
    when 2
      if match_finals
        self.current_round += 1
        self.save
      else return false
      end
    end
    true
  end
  
  def finalize_match_play
    winner_name = nil
    winner_score = nil
    championship = match_play_matchups.find_by(winner_place: 1)
    third_place = match_play_matchups.find_by(winner_place: 3)
    fifth_place = match_play_matchups.find_by(winner_place: 5)
    seventh_place = match_play_matchups.find_by(winner_place: 7)
    first_golfer_event = GolferEvent.new(golfer: championship.winner_golfer, finish: 1)
    second_golfer_event = GolferEvent.new(golfer: championship.loser_golfer, finish: 2)
    third_golfer_event = GolferEvent.new(golfer: third_place.winner_golfer, finish: 3)
    fourth_golfer_event = GolferEvent.new(golfer: third_place.loser_golfer, finish: 4)
    fifth_golfer_event = GolferEvent.new(golfer: fifth_place.winner_golfer, finish: 5)
    sixth_golfer_event = GolferEvent.new(golfer: fifth_place.loser_golfer, finish: 6)
    seventh_golfer_event = GolferEvent.new(golfer: seventh_place.winner_golfer, finish: 7)
    eighth_golfer_event = GolferEvent.new(golfer: seventh_place.loser_golfer, finish: 8)
    golfer_events = [
      first_golfer_event,
      second_golfer_event,
      third_golfer_event,
      fourth_golfer_event,
      fifth_golfer_event,
      sixth_golfer_event,
      seventh_golfer_event,
      eighth_golfer_event
    ]
    golfer_events.each do |event|
      event.season_tournament = self
      event.society = Society.last
      event.golfer_season = GolferSeason.find_or_create_by(golfer: event.golfer, season: self.season)
      event.tournament = self.tournament
      event.course = self.course
      event.completed = true
      event.calculate_points
      print event.inspect
      event.save
      if event.finish == 1
        event_winner = EventWinner.new(golfer: event.golfer, season_tournament: self, golfer_season: event.golfer_season,
                                       event_level: self.event_level)
        event_winner.save
        event.golfer.update_victory_count
        winner_name = event.golfer.name
        winner_score = event.display_score_to_par
      end
    end
    headline = headlines.new()
    headline.generate_event_winner_story(winner_name, tournament_name, winner_score)
    season.golfer_seasons.each { |g| g.update_season }
    self.finalized = true
    self.save ? true : false
    Record.generate_all_records
  end
  
  def unfinalize_event
    event_winners.destroy_all
    headlines.destroy_all
    golfer_events.update_all(points: 0)
    season.golfer_seasons.each { |g| g.update_season }
    calculate_season_points season.year
    self.finalized = false
    self.save ? true : false
  end
  
  def select_default_course
    @course = Tournament.find(params[:id]).course
  end
  
  def formatted_end_date
    end_date.strftime("%m/%d/%Y")
  end
  
  private
  
  def match_round_of_eight
    golfers = season.golfer_seasons.order(rank: :asc).first(8)
    4.times do |n|
      matchup = MatchPlayMatchup.new()
      matchup.favorite_golfer = golfers[n].golfer
      matchup.underdog_golfer = golfers[7 - n].golfer
      matchup.season_tournament_id = self.id
      matchup.favorite_seed = n + 1
      matchup.underdog_seed = 8 - n
      matchup.round = current_round + 1
      return false unless matchup.save
    end
    true
  end
  
  def match_semi_finals
    previous_matchups = self.match_play_matchups.where(round: 1).order(favorite_seed: :asc)
    return false if previous_matchups.where(winner_golfer: nil).count > 0 
    2.times do |n|
      winner_matchup = MatchPlayMatchup.new()
      winner_matchup.favorite_golfer = previous_matchups[n].winner_golfer
      winner_matchup.underdog_golfer = previous_matchups[3 - n].winner_golfer
      winner_matchup.season_tournament_id = self.id
      winner_matchup.favorite_seed = previous_matchups[n].winner_seed
      winner_matchup.underdog_seed = previous_matchups[3 - n].winner_seed
      winner_matchup.round = current_round + 1
      return false unless winner_matchup.save
      loser_matchup = MatchPlayMatchup.new()
      loser_matchup.favorite_golfer = previous_matchups[3 - n].loser_golfer
      loser_matchup.underdog_golfer = previous_matchups[n].loser_golfer
      loser_matchup.season_tournament_id = self.id
      loser_matchup.favorite_seed = previous_matchups[3 - n].loser_seed
      loser_matchup.underdog_seed = previous_matchups[n].loser_seed
      loser_matchup.round = current_round + 1
      loser_matchup.losers_bracket = true
      return false unless loser_matchup.save
    end
    true
  end
  
  def match_finals
    previous_winners_bracket = self.match_play_matchups.where(round: 2, losers_bracket: false).order(favorite_seed: :asc)
    previous_losers_bracket = self.match_play_matchups.where(round: 2, losers_bracket: true).order(favorite_seed: :asc)
    # Make Championship Game
    championship = MatchPlayMatchup.new(season_tournament_id: self.id, round: current_round + 1)
    championship.favorite_golfer = previous_winners_bracket.first.winner_golfer
    championship.underdog_golfer = previous_winners_bracket.last.winner_golfer
    championship.favorite_seed = previous_winners_bracket.first.winner_seed
    championship.underdog_seed = previous_winners_bracket.last.winner_seed
    championship.winner_place = 1
    championship.loser_place = 2
    return false unless championship.save
    
    # Make 3rd Place Game
    third_place = MatchPlayMatchup.new(season_tournament_id: self.id, round: current_round + 1)
    third_place.favorite_golfer = previous_winners_bracket.first.loser_golfer
    third_place.underdog_golfer = previous_winners_bracket.last.loser_golfer
    third_place.favorite_seed = previous_winners_bracket.first.loser_seed
    third_place.underdog_seed = previous_winners_bracket.last.loser_seed
    third_place.winner_place = 3

app/controllers/season_tournaments_controller.rb
class SeasonTournamentsController < ApplicationController
  before_action :select_event, only: [:show, :edit, :update, :destroy, :finalize, :unfinalize, 
                                      :match_play, :generate_matchups, :finalize_match_play]
  
  def index
    @events = SeasonTournament.all
  end
  
  def show
    @golfer_events = @event.golfer_events.includes(:golfer).order(:finish)  
  end
    
  def new
    @event = SeasonTournament.new
    @season = Season.find_by(year: params[:season])
    @season_id = @season.id if @season
  end
  
  def create
    @event = SeasonTournament.new(event_params)
    @event.society = Society.last
    @event.event_level = @event.tournament.tournament_level.name.downcase
    @event.season_order = SeasonTournament.where(season_id: @event.season_id).where("start_date < ?", @event.start_date).count + 1
    if @event.save
      flash[:success] = "Event added!"
      redirect_to schedule_path(@event.season.year)
    else
      render 'new'
    end
  end
  
  def edit; end
    
  def update
    if @event.update(event_params)
      flash['success'] = "Event updated!"
      redirect_to schedule(@event.season.year)
    else
      render 'edit'
    end
  end
  
  def destroy
    @event.destroy ? flash[:success] = "Event deleted!" : flash[:danger] = "There was a problem deleting the event!"
    redirect_to schedule(@event.season.year)
  end
  
  def schedule
    @season = Season.includes(season_tournaments: [:tournament, :course]).find(params[:id])
    @previous_season = Season.find_by(year: @season.year - 1)
    @next_season = Season.find_by(year: @season.year + 1)
    @events = @season.season_tournaments
  end
  
  def match_play
    @round_one_matchups = @event.match_play_matchups.where(round: 1)
    @round_two_winner_matchups = @event.match_play_matchups.where(round: 2, losers_bracket: false)
    @round_two_losers_matchups = @event.match_play_matchups.where(round: 2, losers_bracket: true)
    @championship = @event.match_play_matchups.find_by(winner_place: 1)
    @third_place = @event.match_play_matchups.find_by(winner_place: 3)
    @fifth_place = @event.match_play_matchups.find_by(winner_place: 5)
    @seventh_place = @event.match_play_matchups.find_by(winner_place: 7)
  end
  
  def generate_matchups
    if @event.generate_matchups == true
      flash[:success] = "Matchups Created!"
      redirect_to match_play_path(@event)
    else
      flash[:warning] = "Matchups could not be generated. Please make sure there are at least 8 eligible players!"
      redirect_to match_play_path(@event)
    end
  end
  
  def finalize_match_play
    if @event.finalize_match_play
      flash[:success] = "Event Finalized!"
      redirect_to @event
    else
      flash[:warning] = "Event could not be finalized!"
      redirect_to match_play_path(@event)
    end
  end
  
  def finalize
    @event.finalize_event ? flash[:success] = "Event finalized!": flash[:warning] = "Event not finalized!"
    redirect_to @event
  end
  
  def unfinalize
    @event.unfinalize_event ? flash[:success] = "Event unfinalized!": flash[:warning] = "Error unfinalizing event!"
    redirect_to @event
  end
  
  private
  
    def select_event
      begin
        @event = SeasonTournament.includes(:tournament).find(params[:id])
      rescue StandardError => e
        redirect_to schedule_path(Season.current_year)
        flash[:danger] = e.message
      end
    end
    
    def event_params
      params.require(:season_tournament).permit(:season_order, :rounds, :start_date, :end_date, 
                                        :course_id, :society_id, :tournament_id, :season_id, :match_play)
    end
end

app/helpers/season_tournaments_helper.rb
module SeasonTournamentsHelper
end

app/views/season_tournaments/_form.html.erb
<%= form_for(@event) do |form| %>
  
  <% if @event.errors.any? %>
    <div id="error-explanations">
      <%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:
      <ul>
        <% @event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= form.label :season %>
    <%= form.collection_select :season_id, Season.where(society: Society.first).order(:year), 
        :id, :year, {selected: @season_id}, {class: 'form-field', id: :event_season_id }
    %>
  </div>
  
  <div class="field">
    <%= form.label :tournament %>
    <%= form.collection_select :tournament_id, Tournament.all.order(:name), :id, :latest_name, {}, {class: 'form-field', id: :event_tournament_id }%>
  </div>
  
  <div class="field">
    <%= form.label :course %>
    <%= form.collection_select :course_id, Course.all.order(:name), :id, :name, {}, {class: 'form-field', id: :event_course_id }%>
  </div>
  
  <div class="field">
    <%= form.label :rounds %>
    <%= form.number_field :rounds, min: 1, max: 4, class: 'form-field', id: :event_rounds %>
  </div>
  
  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_field :start_date, class: 'form-field', id: :event_start_date %>
  </div>
  
  <div class="field">
    <%= form.label :end_date %>
    <%= form.date_field :end_date, class: 'form-field', id: :event_end_date %>
  </div>
  
  <div class="field">
    <%= form.label :match_play %>
    <%= form.check_box :match_play, class: 'form-field', id: :event_match_play %>
  </div>
  
  <div class="submit">
    <%= form.submit yield(:button_text), class: 'button submit-button' %>
  </div>
  
<% end %>

app/views/season_tournaments/_matchup_row.html.erb
  <tr>
    <td><%= matchup.favorite_seed %></td>
    <td><%= matchup.favorite_golfer.name %></td>
    <td><%= matchup.underdog_seed %></td>
    <td><%= matchup.underdog_golfer.name %></td>
    <td><%= link_to matchup.result_string, edit_match_play_matchup_path(matchup) %></td>
  </tr>

app/views/season_tournaments/_matchup_th.html.erb
<thead>
  <tr>
    <th>Seed</th>
    <th>Favorite</th>
    <th>Seed</th>
    <th>Underdog</th>
    <th>Result</th>
  </tr>
</thead>

app/views/season_tournaments/edit.html.erb
<% provide(:title, 'Update Event') %>
<% provide(:button_text, 'Update Event') %>

<div class="form-container">
  <h1>Update Event</h1>
  
  <%= render 'form', event: @event %>
</div>

app/views/season_tournaments/match_play.html.erb
<% provide(:title, @event.tournament_name) %>

<div class="table-container">
  <div class="leaderboard-info">
    <div class="event-info">
      <h3><%= link_to @event.tournament_name, @event.tournament %></h3>
      <p><%= "#{@event.course_name} • #{@event.start_date.strftime("%m/%d/%Y")}" %></p>
    </div>
    <% if @event.current_round < 3 %>
      <%= link_to 'Generate Matchups', generate_matchups_path(@event) %>
    <% else %>
      <%= link_to 'Finalize Event', finalize_match_play_path(@event) %>
    <% end %>
  </div>
  <div class="table-wrapper">
    <h3 class="match-play-subhead">Round 1 Matchups</h3>
    <table class="match-play-matchups leaderboard">
      <%= render 'matchup_th' %>
      <tbody>
        <% @round_one_matchups.each do |matchup| %>
          <%= render 'matchup_row', matchup: matchup %>
        <% end %>
      </tbody>
    </table>
    <h3 class="match-play-subhead">Round 2 Matchups</h3>
    <table class="match-play-matchups leaderboard">
      <%= render 'matchup_th' %>
      <tbody>
        <tr>
          <th colspan=5 class="bracket-title">Winners Bracket</th>
        </tr>
        <% @round_two_winner_matchups.each do |matchup| %>
          <%= render 'matchup_row', matchup: matchup %>
        <% end %>
        <tr>
          <th colspan=5 class="bracket-title">Losers Bracket</th>
        </tr>
        <% @round_two_losers_matchups.each do |matchup| %>
          <%= render 'matchup_row', matchup: matchup %>
        <% end %>
      </tbody>
    </table>
    <h3 class="match-play-subhead">Finals</h3>
    <table class="match-play-matchups leaderboard">
      <%= render 'matchup_th' %>
      <tbody>
        <tr>
          <th colspan=5 class="bracket-title">Finals</th>
        </tr>
        <%= render 'matchup_row', matchup: @championship if @championship %>
        <tr>
          <th colspan=5 class="bracket-title">3rd Place</th>
        </tr>
        <%= render 'matchup_row', matchup: @third_place  if @third_place %>
        <tr>
          <th colspan=5 class="bracket-title">5th Place</th>
        </tr>
        <%= render 'matchup_row', matchup: @fifth_place if @fifth_place %>
        <tr>
          <th colspan=5 class="bracket-title">7th Place</th>
        </tr>
        <%= render 'matchup_row', matchup: @seventh_place if @seventh_place %>
      </tbody>
    </table>
  </div>
</div>
  

app/views/season_tournaments/new.html.erb
<% provide(:title, 'Create Event') %>
<% provide(:button_text, 'Create Event') %>

<div class="form-container">
  <h1>Create an Event</h1>

  <%= render 'form', event: @event %>
</div>

app/views/season_tournaments/schedule.html.erb
<% provide(:title, 'Schedule') %>

<div class="table-container">
  <div class="table-info">
    <h3><%= @season.year %> Schedule</h3>
    <%= link_to 'New Tournament', new_season_tournament_path(:season => @season.year) %>
  </div>
  <div class="table-wrapper">
    <table class="index-table">
      <thead>
        <tr>
          <th>Date</th>
          <th>Type</th>
          <th>Event</th>
          <th>Course</th>
          <th>Rounds</th>
          <th>Champion</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @events.all.each do |event| %>
          <tr class=<%= event.event_level %>>
            <td><%= event.start_date.strftime('%m/%d/%Y') %></td>
            <td><%= event.type_stub %></td>
            <td><%= link_to event.tournament_name, event, class: "block-link" %></td>
            <td><%= event.course_name %></td>
            <td><%= event.rounds %></td>
            <td><%= event.display_winners %></td>
            <td><%= link_to 'Edit', edit_season_tournament_path(event) %> | 
                <%= link_to 'Delete', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="button-container nav-button-container">
  <%= link_to "Previous Season", schedule_path(@previous_season), class: "button previous-button"  if @previous_season %>
  <%= link_to "Next Season", schedule_path(@next_season), class: "button next-button" if @next_season %>
</div>

app/views/season_tournaments/show.html.erb
<% provide(:title, @event.tournament_name) %>

<div class="table-container">
  <div class="leaderboard-info">
    <div class="event-info">
      <h3><%= link_to @event.tournament_name, @event.tournament %></h3>
      <p><%= "#{@event.course_name} • #{@event.start_date.strftime("%m/%d/%Y")}" %></p>
    </div>
    <% if !@event.match_play && !@event.finalized %>
      <%= link_to 'New Golfer', new_season_tournament_golfer_event_path(@event) %>
    <% elsif @event.match_play %>
      <%= link_to 'Show Matchups', match_play_path(@event) %>
    <% end %>
  </div>
  <div class="table-wrapper">
    <table class="leaderboard">
      <thead>
        <tr>
          <th>POS</th>
          <th>Golfer</th>
          <th>Total</th>
          <% for i in 1..@event.rounds %>
            <th><%= "R#{i}" %></th>
          <% end %>
          <th>Strokes</th>
          <% if @event.finalized %>
            <th>Points</th>
          <% else %>
            <th>Actions</th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% @golfer_events.each do |event| %>
          <tr>
            <td><%= event.finish %></td>
            <td><%= link_to event.golfer.name, event.golfer, class: "block-link" %></td>
            <td><%= event.display_score_to_par %></td>
            <% event.golfer_rounds.order(:round_order).each do |round| %>
            <td><%= round.score %></td>
            <% end %>
            <% (@event.rounds - event.golfer_rounds.count).times do %>
            <td></td>
            <% end %>
            <td><%= event.score %></td>
            <% if @event.finalized %>
              <td><%= event.points %></td>
            <% else %>
              <td><%= link_to 'Edit', edit_season_tournament_golfer_event_path(@event, event) %> | 
                  <%= link_to 'Delete', [@event, event], method: :delete, data: {confirm: 'Are you sure?' } %>
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<div class="button-container">
  <% if !@event.finalized %>
    <%= link_to "Finalize Event", finalize_event_path(@event), class: "button finalize-button" %>
  <% else %>
    <%= link_to "Unfinalize Event", unfinalize_event_path(@event), class: "button finalize-button" %>
  <% end %> 
</div>