config/routes.rb
Rails.application.routes.draw do
  root 'seasons#show', id: Season.current_id
  resources :seasons
  resources :courses
  resources :golfers do
    get 'events' => 'golfers#events'
  end
  resources :headlines, only: [:new, :create, :destroy]
  resources :match_play_matchups, only: [:edit, :update]
  resources :tournaments 
  resources :ryder_cup_sessions do
    resources :ryder_cup_rounds
  end
  resources :season_tournaments, :path => "events" do
    resources :golfer_events
  end
  get 'record_book' => 'records#index'
  get 'course_difficulty' => 'courses#difficulty_rankings'
  get 'ryder_cup/:id' => 'ryder_cups#show', as: :ryder_cup
  get 'schedule/:id' => 'season_tournaments#schedule',  as: :schedule
  get 'events/:id/show_matchups' => 'season_tournaments#match_play', as: :match_play
  get 'events/:id/generate_matchups' => 'season_tournaments#generate_matchups', as: :generate_matchups
  get 'events/:id/finalize_match_play' => 'season_tournaments#finalize_match_play', as: :finalize_match_play
  get 'roster' => 'golfers#index'
  get 'finalize/:id' => 'season_tournaments#finalize', as: :finalize_event
  get 'unfinalize/:id' => 'season_tournaments#unfinalize', as: :unfinalize_event
  get 'select_default_course' => 'season_tournaments#select_default_course'
  match 'active_headlines' => 'headlines#active_headlines', via: [:get, :post]
end 

app/models/tournament.rb
class Tournament < ApplicationRecord
  belongs_to :society
  belongs_to :tournament_level
  belongs_to :course, optional: true
  has_many :season_tournaments, dependent: :destroy
  has_many :golfer_events
  has_many :golfer_rounds
  validates :name, uniqueness: true
  
  def home_course
    course ? course.name : 'Rotates'
  end
  
  def level
    tournament_level.name if tournament_level
  end
  
  def latest_name
    updated_name ? updated_name : name
  end
  
  def current_name(year)
    if updated_name.nil?
      name
    elsif year < name_updated_year
      name
    else
      updated_name
    end
  end
  
  def best_rounds
    record = []
    low_score = golfer_rounds.order(score: :asc).first.score if golfer_rounds.count > 0
    rounds = golfer_rounds.where("score = ?", low_score)
    rounds.each do |round|
      new_round = {}
      new_round[:golfer] = round.golfer.name
      new_round[:score] = low_score
      new_round[:score_to_par] = round.display_score_to_par
      new_round[:event] = round.season_tournament.tournament_name_with_year
      new_round[:course] = round.course.name
      new_round[:golfer_id] = round.golfer.id
      new_round[:event_id] = round.season_tournament.id
      new_round[:course_id] = round.course.id
      record << new_round
    end
    record
  end
  
  def best_tournaments
    record = []
    low_score = golfer_events.order(score_to_par: :asc).first.score_to_par if golfer_events.count > 0
    tournaments = golfer_events.where("score_to_par = ?", low_score)
    tournaments.each do |tournament|
      new_tournament = {}
      new_tournament[:golfer] = tournament.golfer.name
      new_tournament[:score] = tournament.score
      new_tournament[:score_to_par] = tournament.display_score_to_par
      new_tournament[:event] = tournament.season_tournament.tournament_name_with_year
      new_tournament[:course] = tournament.course.name
      new_tournament[:golfer_id] = tournament.golfer.id
      new_tournament[:event_id] = tournament.season_tournament.id
      new_tournament[:course_id] = tournament.course.id
      record << new_tournament
    end
    record
  end
  
  def winners
    events = []
    season_tournaments.order(start_date: :desc).each do |tournament|
      event = {}
      event[:id] = tournament.id
      event[:year] = tournament.year
      event[:winners] = tournament.display_winners
      event[:score] = tournament.winning_score
      event[:score_to_par] = tournament.winning_score_to_par
      event[:course] = tournament.course_name
      event[:course_id] = tournament.course.id
      events << event
    end
    events
  end
  
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  before_action :select_tournament, only: [:show, :edit, :update, :destroy]
  
  def index
    @tournaments = Tournament.all.includes(:tournament_level).order(:name)
  end
  
  def show; end
    
  def new
    @tournament = Tournament.new
  end
  
  def create
    @tournament = Tournament.new(tournament_params)
    @tournament.society = Society.last
    if @tournament.save
      flash[:success] = "Tournament added!"
      redirect_to tournaments_path
    else
      render 'new'
    end
  end
  
  def edit; end
    
  def update
    if @tournament.update(tournament_params)
      flash['success'] = "Tournament updated!"
      redirect_to tournaments_path
    else
      render 'edit'
    end
  end
  
  def destroy
  
  end
  
  private
    def select_tournament
      begin
        @tournament = Tournament.includes(:golfer_rounds, :golfer_events).find(params[:id])
      rescue StandardError => e
        redirect_to tournaments_path
        flash[:danger] = e.message
      end
    end
    
    def tournament_params
      params.require(:tournament).permit(:name, :society_id, :course_id, :tournament_level_id)
    end
    
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/tournaments/_form.html.erb
<%= form_for(@tournament) do |form| %>
  
  <% if @tournament.errors.any? %>
    <div id="error-explanations">
      <%= pluralize(@tournament.errors.count, "error") %> prohibited this tournament from being saved:
      <ul>
        <% @tournament.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-field', id: :tournament_name %>
  </div>

  <div class="field">
    <%= form.label :course %>
    <%= form.collection_select :course_id, Course.all.order(:name), :id, :name, {include_blank: 'Rotates'}, {class: 'form-field', id: :tournament_course_id }%>
  </div>
  
  <div class="field">
    <%= form.label :type %>
    <%= form.collection_select :tournament_level_id, TournamentLevel.all, :id, :name, {}, {class: 'form-field', id: :tournament_tournament_level_id }%>
  </div>
  
  <div class="submit">
    <%= form.submit yield(:button_text), class: 'button submit-button' %>
  </div>
<% end %>

app/views/tournaments/edit.html.erb
<% provide(:title, 'Update Tournament') %>
<% provide(:button_text, 'Update Tournament') %>

<div class="form-container">
  <h1>Update Tournament</h1>
  
  <%= render 'form', tournament: @tournament %>
</div>

app/views/tournaments/index.html.erb
<% provide(:title, 'Tournaments') %>

<div class="table-container">
  <div class="table-info">
    <h3>BTGA Tournaments</h3>
    <%= link_to 'New Tournament', new_tournament_path %>
  </div>
  <div class="table-wrapper">
    <table class="index-table">
      <thead>
        <tr>
          <th>Tournament</th>
          <th>Course</th>
          <th>Type</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @tournaments.all.each do |tournament| %>
          <tr>
            <td><%= link_to tournament.name, tournament %></td>
            <td><%= tournament.home_course %></td>
            <td><%= tournament.level %></td>
            <td><%= link_to 'Edit', edit_tournament_path(tournament) %> | 
                <%= link_to 'Delete', tournament, method: :delete, data: { confirm: 'Are you sure?' } %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/tournaments/new.html.erb
<% provide(:title, 'Create Tournament') %>
<% provide(:button_text, 'Create Tournament') %>

<div class="form-container">
  <h1>Create a Tournament</h1>

  <%= render 'form', course: @tournament %>
</div>

app/views/tournaments/show.html.erb
<% provide(:title, @tournament.name) %>

<div class="show-profile">
  <div class="show-headline">
    <h1><%= @tournament.current_name(Season.current_year) %></h1>
  </div>
  <div class="table-container">
    <div class="table-info">
      <h3>Tourament Records</h3>
    </div>
    <div class="table-wrapper">
      <table class="index-table">
        <thead>
          <tr>
            <th>Record</th>
            <th>Golfer</th>
            <th>Score</th>
            <th>To Par</th>
            <th>Course</th>
            <th>Event</th>
          </tr>
        </thead>
        <tbody>
          <% @tournament.best_rounds.each do |round| %>
            <tr>
              <td>Best Round</td>
              <td><%= link_to round[:golfer], golfer_path(round[:golfer_id]) %></td>
              <td><%= round[:score] %></td>
              <td><%= round[:score_to_par] %></td>
              <td><%= link_to round[:course], course_path(round[:course_id]) %></td>
              <td><%= link_to round[:event], season_tournament_path(round[:event_id]) %></td>
            </tr>
          <% end %>
          <% @tournament.best_tournaments.each do |tournament| %>
            <tr>
              <td>Best Tournament</td>
              <td><%= link_to tournament[:golfer], golfer_path(tournament[:golfer_id]) %></td>
              <td><%= tournament[:score] %></td>
              <td><%= tournament[:score_to_par] %></td>
              <td><%= link_to tournament[:course], course_path(tournament[:course_id]) %></td>
              <td><%= link_to tournament[:event], season_tournament_path(tournament[:event_id]) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="table-container">
    <div class="table-info">
      <h3>Tournament Winners</h3>
    </div>
    <div class="table-wrapper">
      <table class="index-table">
        <thead>
          <tr>
            <th>Year</th>
            <th>Winner</th>
            <th>Total</th>
            <th>Strokes</th>
            <th>Course</th>
          </tr>
        </thead>
        <tbody>
          <% @tournament.winners.each do |winner| %>
            <tr>
              <td><%= link_to winner[:year], season_tournament_path(winner[:id]) %></td>
              <td><%= winner[:winners] %></td>
              <td><%= winner[:score_to_par] %></td>
              <td><%= winner[:score] %></td>
              <td><%= link_to winner[:course], course_path(winner[:course_id]) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>