config/routes.rb
Rails.application.routes.draw do
  root 'seasons#show', id: Season.current_id
  resources :seasons
  resources :courses
  resources :golfers do
    get 'events' => 'golfers#events'
  end
  resources :headlines, only: [:new, :create, :destroy]
  resources :match_play_matchups, only: [:edit, :update]
  resources :tournaments 
  resources :ryder_cup_sessions do
    resources :ryder_cup_rounds
  end
  resources :season_tournaments, :path => "events" do
    resources :golfer_events
  end
  get 'record_book' => 'records#index'
  get 'course_difficulty' => 'courses#difficulty_rankings'
  get 'ryder_cup/:id' => 'ryder_cups#show', as: :ryder_cup
  get 'schedule/:id' => 'season_tournaments#schedule',  as: :schedule
  get 'events/:id/show_matchups' => 'season_tournaments#match_play', as: :match_play
  get 'events/:id/generate_matchups' => 'season_tournaments#generate_matchups', as: :generate_matchups
  get 'events/:id/finalize_match_play' => 'season_tournaments#finalize_match_play', as: :finalize_match_play
  get 'roster' => 'golfers#index'
  get 'finalize/:id' => 'season_tournaments#finalize', as: :finalize_event
  get 'unfinalize/:id' => 'season_tournaments#unfinalize', as: :unfinalize_event
  get 'select_default_course' => 'season_tournaments#select_default_course'
  match 'active_headlines' => 'headlines#active_headlines', via: [:get, :post]
end 

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :select_course, only: [:show, :edit, :update, :destroy]
  
  def index
    @courses = Course.all.order(:name)
  end
  
  def show; end
  
  def new
    @course = Course.new
  end
  
  def create
    @course = Course.new(course_params)
    if @course.save
      flash[:success] = "Course added!"
      redirect_to courses_path
    else
      render 'new'
    end
  end
  
  def edit; end
    
  def update
    if @course.update(course_params)
      flash['success'] = "Course updated!"
      redirect_to courses_path
    else
      render 'edit'
    end
  end
  
  def destroy
    @course.destroy ? flash[:success] = "Course deleted!" : flash[:danger] = "There was a problem deleting the course."
    redirect_to courses_path
  end
  
  def difficulty_rankings
    season_one_id = Season.all.order(year: :asc).first.id
    @courses = Course.joins(golfer_rounds: [:golfer_season])
                     .select("courses.*, avg(golfer_rounds.score_to_par) AS average_score")
                     .where.not(golfer_seasons: {season_id: season_one_id})
                     .group('courses.id')
                     .order('avg(golfer_rounds.score_to_par) desc').to_a
  end
  
  private
  
    def select_course
      begin
        @course = Course.find(params[:id])
      rescue StandardError => e
        redirect_to courses_path
        flash[:danger] = e.message
      end
    end
    
    def course_params
      params.require(:course).permit(:name, :yardage, :par, :difficulty, :star_rating)
    end
  
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= form_for(@course) do |form| %>

  <% if @course.errors.any? %>
    <div id="error-explanations">
      <%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:
      <ul>
        <% @course.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-field', id: :course_name %>
  </div>
  
  <div class="field">
    <%= form.label :yardage %>
    <%= form.number_field :yardage, class: 'form-field', id: :course_yardage %>
  </div>
  
  <div class="field">
    <%= form.label :par %>
    <%= form.number_field :par, class: 'form-field', id: :course_name %>
  </div>
  
  <div class="field">
    <%= form.label :difficulty %>
    <%= form.select :difficulty, Course.difficulty_options, {}, {class: 'form-field', id: :course_difficulty} %>
  </div>
  
  <div class="field">
    <%= form.label :star_rating %>
    <%= form.number_field :star_rating, min: 0, max: 10, step: 0.1, class: 'form-field', id: :course_star_rating %>
  </div>
  
  <div class="submit">
    <%= form.submit yield(:button_text), class: 'button submit-button' %>
  </div>
  
<% end %>

app/views/courses/difficulty_rankings.html.erb
<% provide(:title, 'Course Difficulty') %>

<div class="table-container">
  <div class="table-info">
    <h3>BTGA Course Difficulty</h3>
  </div>
  <div class="table-wrapper">
    <table class="index-table">
      <thead>
        <tr>
          <th>Course</th>
          <th>Par</th>
          <th>Yardage</th>
          <th>Avg Score</th>
        </tr>
      </thead>
      <tbody>
        <% @courses.each do |course| %>
          <% avg = course.average_score.to_f.round(1) %>
          <% avg = avg < 0 ? avg.to_s : "+#{avg}" %>
          <tr>
            <td><%= link_to course.name, course_path(course.id) %></td>
            <td><%= course.par %></td>
            <td><%= course.yardage %></td>
            <td><%= avg %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/courses/edit.html.erb
<% provide(:title, 'Update Course') %>
<% provide(:button_text, 'Update Course') %>

<div class="form-container">
  <h1>Update Course</h1>
  
  <%= render 'form', course: @course %>
</div>

app/views/courses/index.html.erb
<% provide(:title, 'Courses') %>

<div class="table-container">
  <div class="table-info">
    <h3>BTGA Course List</h3>
    <%= link_to 'New Course', new_course_path %>
  </div>
  <div class="table-wrapper">
    <table class="index-table">
      <thead>
        <tr>
          <th>Course</th>
          <th>Par</th>
          <th>Yardage</th>
          <th>Difficulty</th>
          <th>Rating</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @courses.all.each do |course| %>
          <tr>
            <td><%= link_to course.name, course %></td>
            <td><%= course.par %></td>
            <td><%= course.yardage %></td>
            <td><%= course.difficulty %></td>
            <td><%= course.star_rating %></td>
            <td><%= link_to 'Edit', edit_course_path(course) %> | 
                <%= link_to 'Delete', course, method: :delete, data: { confirm: 'Are you sure?' } %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<div class="button-container">
  <%= link_to "Difficulty Rankings", "/course_difficulty", class: "button" %>
</div>

app/views/courses/new.html.erb
<% provide(:title, 'Create Course') %>
<% provide(:button_text, 'Create Course') %>

<div class="form-container">
  <h1>Create a Course</h1>

  <%= render 'form', course: @course %>
</div>

app/views/courses/show.html.erb
<% provide(:title, @course.name) %>

<div class="show-profile">
  <div class="show-headline">
    <h1><%= @course.name %></h1>
    <div class="golfer-info">
      <div class="info-line">
        <div class="info-item">
          <p class="title">Par</p>
          <p><%= @course.par %></p>
        </div>
        <div class="info-item">
          <p class="title">Yardage</p>
          <p><%= @course.yardage %></p>
        </div>
      </div>
    </div>
  </div>
<div class="table-container">
    <div class="table-info">
      <h3>Course Records</h3>
    </div>
    <div class="table-wrapper">
      <table class="index-table">
        <thead>
          <tr>
            <th>Record</th>
            <th>Golfer</th>
            <th>Score</th>
            <th>To Par</th>
            <th>Event</th>
          </tr>
        </thead>
        <tbody>
          <% @course.best_rounds.each do |round| %>
            <tr>
              <td>Best Round</td>
              <td><%= link_to round[:golfer], golfer_path(round[:golfer_id]) %></td>
              <td><%= round[:score] %></td>
              <td><%= round[:score_to_par] %></td>
              <td><%= link_to round[:event], season_tournament_path(round[:event_id]) %></td>
            </tr>
          <% end %>
          <% @course.best_tournaments.each do |tournament| %>
            <tr>
              <td>Best Tournament</td>
              <td><%= link_to tournament[:golfer], golfer_path(tournament[:golfer_id]) %></td>
              <td><%= tournament[:score] %></td>
              <td><%= tournament[:score_to_par] %></td>
              <td><%= link_to tournament[:event], season_tournament_path(tournament[:event_id]) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="table-container">
    <div class="table-info">
      <h3>Tournament Winners</h3>
    </div>
    <div class="table-wrapper">
      <table class="index-table">
        <thead>
          <tr>
            <th>Event</th>
            <th>Winner</th>
            <th>Total</th>
            <th>Strokes</th>
            <th>Course</th>
          </tr>
        </thead>
        <tbody>
          <% @course.winners.each do |winner| %>
            <tr>
              <td><%= link_to winner[:event], season_tournament_path(winner[:id]) %></td>
              <td><%= winner[:winners] %></td>
              <td><%= winner[:score_to_par] %></td>
              <td><%= winner[:score] %></td>
              <td><%= link_to winner[:course], course_path(winner[:course_id]) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>