config/routes.rb
Rails.application.routes.draw do
  root 'seasons#show', id: Season.current_id
  resources :seasons
  resources :courses
  resources :golfers do
    get 'events' => 'golfers#events'
  end
  resources :headlines, only: [:new, :create, :destroy]
  resources :match_play_matchups, only: [:edit, :update]
  resources :tournaments 
  resources :ryder_cup_sessions do
    resources :ryder_cup_rounds
  end
  resources :season_tournaments, :path => "events" do
    resources :golfer_events
  end
  get 'record_book' => 'records#index'
  get 'course_difficulty' => 'courses#difficulty_rankings'
  get 'ryder_cup/:id' => 'ryder_cups#show', as: :ryder_cup
  get 'schedule/:id' => 'season_tournaments#schedule',  as: :schedule
  get 'events/:id/show_matchups' => 'season_tournaments#match_play', as: :match_play
  get 'events/:id/generate_matchups' => 'season_tournaments#generate_matchups', as: :generate_matchups
  get 'events/:id/finalize_match_play' => 'season_tournaments#finalize_match_play', as: :finalize_match_play
  get 'roster' => 'golfers#index'
  get 'finalize/:id' => 'season_tournaments#finalize', as: :finalize_event
  get 'unfinalize/:id' => 'season_tournaments#unfinalize', as: :unfinalize_event
  get 'select_default_course' => 'season_tournaments#select_default_course'
  match 'active_headlines' => 'headlines#active_headlines', via: [:get, :post]
end 

app/models/ryder_cup_session.rb
class RyderCupSession < ApplicationRecord
  ALLOWED_TYPES = ["Fourball", "Foursome", "Scramble", "Singles"]
  has_many :ryder_cup_rounds, dependent: :destroy
  belongs_to :ryder_cup
  belongs_to :course, optional: true
  validates :scoring_type, :inclusion => { :in => ALLOWED_TYPES }
  
  def name
    "#{ryder_cup.season.year} #{scoring_type}"
  end
  
  def course_name
    if course
      course.name
    else
      "N/A"
    end
  end
end

app/controllers/ryder_cup_sessions_controller.rb
class RyderCupSessionsController < ApplicationController
  def show
    @session = RyderCupSession.includes(:ryder_cup_rounds).find(params[:id])
    @rounds = @session.ryder_cup_rounds
    @ryder_cup = @session.ryder_cup
    @season = @ryder_cup.season
  end
end

app/helpers/ryder_cup_sessions_helper.rb
module RyderCupSessionsHelper
end

app/views/ryder_cup_sessions/show.html.erb
<% provide(:title, @session.name) %>

<div class="table-container">
  <div class="table-info">
    <div class="event-info">
      <h3><%= @session.name %></h3>
      <p><%= @session.course_name %></p>
    </div>
    <%= link_to 'New Round', new_ryder_cup_session_ryder_cup_round_path(@session) %>
  </div>
  <div class="table-wrapper">
    <table class="index-table">
      <thead>
        <tr>
          <th class="usa">PTS</th>
          <th class="usa">USA</th>
          <th class="usa">Score</th>
          <th class="europe">Score</th>
          <th class="europe">Europe</th>
          <th class="europe">PTS</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @rounds.all.each do |round| %>
          <tr>
            <td><%= round.usa_points %></td>
            <td><%= round.usa_golfers %></td>
            <td><%= round.usa_score %></td>
            <td><%= round.europe_score %></td>
            <td><%= round.europe_golfers %></td>
            <td><%= round.europe_points %></td>
            <td><%= link_to "Edit", edit_ryder_cup_session_ryder_cup_round_path(@session, round) %> |
                <%= link_to "Delete", [@session, round], method: :delete, data: {confirm: 'Are you sure?'} %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<div class="button-container">
  <%= link_to "Back to #{@ryder_cup.name}", ryder_cup_path(@season.year), class: "button finalize-button" %>
</div>